homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize:    
    binary_sensor.floorplan:
      custom_ui_state_card: floorplan
      config: !include floorplan.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  # Weather Prediction (YR)
  - platform: yr
    monitored_conditions:
      - temperature
      - precipitation

  # Weather Prediction (OpenWeatherMap)
  - platform: openweathermap
    api_key: !secret home_openweathermap_key
    monitored_conditions: 
      - weather
      - temperature

  # OctoPrint Sensor
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

  # Steam account
  - platform: steam_online
    api_key: !secret home_steam_api_key
    accounts:
      - !secret home_steam_account_id

binary_sensor:
  # Floorplan
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

  # OctoPrint Binary Sensor
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

media_player:
  # Spotify
  - platform: spotify
    client_id: !secret home_spotify_id
    client_secret: !secret home_spotify_secret

  # Google Cast
  - platform: cast

# Text to speech
tts:
  platform: google

# # My customizations
# Emulate Hue
emulated_hue:

# MQTT Broker
mqtt:

# Floorplan
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:security-home
    url_path: floorplan
    config: !include floorplan.yaml

# Octoprint
octoprint:
  host: !secret home_octoprint_host
  api_key: !secret home_octoprint_api_key

# Notifications
notify:
  # Android TV notification
  - platform: nfandroidtv
    name: livingroom
    host: !secret home_tv_host

ifttt:
  key: !secret home_ifttt_key

group: !include groups.yaml
automation: !include automations.yaml
